package apihandler

import "github.com/sethjback/gobble/httpapi"

// Routes are teh agent's routes
var Routes = httpapi.Routes{
	httpapi.Route{
		"Status",
		"GET",
		"/status",
		coordinatorStatus},
	//
	//AGENTS
	//
	httpapi.Route{
		"Agents",
		"GET",
		"/agents",
		agentList},
	httpapi.Route{
		"AddAgent",
		"POST",
		"/agents",
		addAgent},
	httpapi.Route{
		"GetAgent",
		"GET",
		"/agents/{agentID}",
		getAgent},
	httpapi.Route{
		"UpdateAgent",
		"PUT",
		"/agents/{agentID}",
		updateAgent},
	//
	//BACKUPS
	//
	httpapi.Route{
		"CreateBackup",
		"POST",
		"/backups",
		addBackup},
	httpapi.Route{
		"ModifyBackup",
		"PUT",
		"/backups/{backupID}",
		modifyBackup},
	httpapi.Route{
		"GetBackup",
		"GET",
		"/backups/{backupID}",
		getBackup},
	httpapi.Route{
		"DeleteBackup",
		"DELETE",
		"/backups/{backupID}",
		deleteBackup},
	httpapi.Route{
		"RunBackup",
		"POST",
		"/backups/{backupID}",
		runBackup},
	httpapi.Route{
		"BackupList",
		"GET",
		"/backups",
		listBackups},
	//
	// Restores
	//
	httpapi.Route{
		"RunRestore",
		"POST",
		"/restores",
		restore},
	//
	//JOBS
	//
	httpapi.Route{
		"JobStatus",
		"GET",
		"/jobs/{jobID}",
		jobStatus},
	httpapi.Route{
		"AddJobFile",
		"POST",
		"/jobs/{jobID}/files",
		addJobFile},
	httpapi.Route{
		"FinishJob",
		"POST",
		"/jobs/{jobID}/complete",
		finishJob},
	httpapi.Route{
		"JobQuery",
		"GET",
		"/jobs",
		jobQuery},
	httpapi.Route{
		"JobFiles",
		"GET",
		"/jobs/{jobID}/files",
		jobFiles},

	//
	// SCHEDULES
	//
	httpapi.Route{
		"ScheduleList",
		"GET",
		"/schedules",
		scheduleList},
	httpapi.Route{
		"AddSchedule",
		"POST",
		"/schedules",
		addSchedule},
	httpapi.Route{
		"GetSchedule",
		"GET",
		"/schedules/{sID}",
		getSchedule},
	httpapi.Route{
		"DeleteSchedule",
		"DELETE",
		"/schedules/{sID}",
		deleteSchedule},
	httpapi.Route{
		"UpdateSchedule",
		"PUT",
		"/schedules/{sID}",
		updateSchedule},
	httpapi.Route{
		"GC",
		"POST",
		"/gc",
		gc}}
